# Generated by Django 5.0.6 on 2024-06-12 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpersonnage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personnageordre',
            name='id',
        ),
        migrations.AddField(
            model_name='documentpersonnage',
            name='CodeDocumentPersonnage',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='personnageordre',
            name='CodePersonnageOrdre',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='CodeCategorieDocument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_documents', to='backend.categoriedocument'),
        ),
        migrations.AlterField(
            model_name='documentpersonnage',
            name='CodeDocument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_document_personnage', to='backend.document'),
        ),
        migrations.AlterField(
            model_name='documentpersonnage',
            name='CodePersonnage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_document_personnage', to='backend.personnage'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='CodeCotisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_paiement', to='backend.cotisation'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='CodePeriode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_paiement', to='backend.periode'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='CodePersonnage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_paiement', to='backend.personnage'),
        ),
        migrations.AlterField(
            model_name='personnage',
            name='PhotoFileName',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='personnageordre',
            name='CodeOrdre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_personnage_ordre', to='backend.ordreinfirmier'),
        ),
        migrations.AlterField(
            model_name='personnageordre',
            name='CodePersonnage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_personnage_ordre', to='backend.personnage'),
        ),
    ]
