# Generated by Django 5.0.6 on 2024-06-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_documentpersonnage_dateenreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='Annee',
            field=models.IntegerField(default=1960),
        ),
        migrations.AddField(
            model_name='periode',
            name='Mois',
            field=models.IntegerField(default=1),
        ),
    ]
