# Generated by Django 5.0.6 on 2024-06-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_periode_annee_periode_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='Monnaie',
            field=models.CharField(default='CDF', max_length=100),
        ),
        migrations.AddField(
            model_name='paiement',
            name='Monnaie',
            field=models.CharField(default='CDF', max_length=100),
        ),
    ]
